FinalProject/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('', include('home.urls')),
    path('', include('echipa.urls')),
    path('', include('jucator.urls')),
    path("", include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),
    path('', include('sport.urls')),
    path('', include('locatie.urls'))

]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path("", views.HomeTemplateView.as_view(), name="home")
]

echipa/models.py
from django.db import models




class Echipa(models.Model):
    gen_choices = (("male", "Male"), ("female", "Female"))
    dificulty_choices = (("incepator", "Incepator"), ("intermediar", "Intermediar"), ("avanasat", "Avansat"))

    nume = models.CharField(max_length=20)
    numar_min_de_jucatori = models.IntegerField()
    numar_max_de_jucatori = models.IntegerField()
    descriere = models.TextField(max_length=1000)
    gen = models.CharField(max_length=10, choices=gen_choices)
    dificultate = models.CharField(max_length=20, choices=dificulty_choices)
    deschisa = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nume} {self.gen} {self.dificultate}"

jucator/models.py
from django.db import models



class Jucator(models.Model):
    gen_choices = (("barbat", "Barbat"), ("femeie", "Femeie"))

    prenume = models.CharField(max_length=20)
    nume = models.CharField(max_length=20)
    porecla = models.CharField(max_length=20)
    varsta = models.IntegerField()
    localitate = models.TextField(max_length=30)
    descriere = models.TextField(max_length=1000)
    gen = models.CharField(max_length=10, choices=gen_choices)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.prenume} {self.nume}"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include "sidebar.html" %}
{% block content %}
{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
</html>

templates/sidebar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<header class='header-fixed'>
    <div class="container">
        <a class="logo animated fadeInLeft" href="#">Find your Team</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                {#                {%  if request.user.is_authenticated and request.user,is_superuser %}#}
{#                {% if request.user.is_authenticated %}#}
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">

                        Jucatori
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
{#                    {% if perms.jucator.add_jucator %}#}
                        <li><a class="dropdown-item" href="{% url "creaza_jucator" %}">Adauga un jucator</a></li>
{#                    {% endif %}#}
                    <li><a class="dropdown-item" href="{% url "lista_cu_jucatori" %}">Lista de jucatori</a></li>
{#                {% endif %}#}
                </ul>
                </li>
                {#                  {%  if request.user.is_authenticated and request.user,is_superuser %}#}
{#                {% if request.user.is_authenticated %}#}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">

                            Echipe

                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
{#                            {% if perms.echipa.add_echipa %}#}
                                <li><a class="dropdown-item" href="{% url 'creaza_echipa' %}">Adauga o echipa</a>
                                </li>
{#                            {% endif %}#}
                            <li><a class="dropdown-item" href="{% url "lista_cu_echipe" %}">Lista cu echipe</a></li>

                        </ul>
                    </li>
{#                {% endif %}#}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">


                            Locatii

                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
{#                            {% if perms.echipa.add_echipa %}#}
                                <li><a class="dropdown-item" href="{% url 'creaza_locatie' %}">Adauga o locatie</a>
                                </li>
{#                            {% endif %}#}
                          <li><a class="dropdown-item" href="{% url "lista_cu_locatii" %}">Lista cu locatii</a></li>

                        </ul>
                    </li>
{#                {% endif %}#}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">

                            Sporturi

                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
{#                            {% if perms.echipa.add_echipa %}#}
                                <li><a class="dropdown-item" href="{% url 'creaza_sport' %}">Adauga sportul dorit</a>
                                </li>
{#                            {% endif %}#}
                        <li><a class="dropdown-item" href="{% url "lista_cu_sporturi" %}">Lista cu sporturi</a></li>

                        </ul>
                    </li>
{#                {% endif %}#}


            </ul>

{#            {% if request.user.is_authenticated %}#}
            <a href="{% url 'logout' %}" class="btn btn-success">Iesire din cont, {{ user.username }}</a>
{#            {% else %}#}
                <a href="{% url 'creaza_user' %}" class="btn btn-secondary">Creaza cont nou</a>
                <a href="{% url 'login' %}" class="btn btn-success">Intrare in cont</a>
{#            {% endif %}#}

        </div>
    </div>
</nav>